name: Deploy step
on:
  workflow_call:
    inputs:
      environment:
        description: "Github environment to deploy to"
        type: string
        required: true
      service:
        description: "Service to run CI on"
        type: string
        required: true
      image_tag:
        type: string
        required: true

env:
  GOPRIVATE: "github.com/cfacorp,buf.cfadevelop.com/gen/go"
  GOPROXY: "https://${{ secrets.ARTIFACTORY_USER }}:${{ secrets.ARTIFACTORY_TOKEN }}@cfa.jfrog.io/artifactory/api/go/go-customer"
  GONOPROXY: none

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cancel pending deployments to ${{ inputs.environment }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./cancel_active_workflow_runs.sh ${{ inputs.environment }} ${{ inputs.service }}

      - name: Fake deploy step
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying to ${{ inputs.environment }}..."

  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment to ${{ inputs.environment }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./create_deployment.sh ${{ inputs.environment }} ${{ inputs.service }} ${{ inputs.image_tag }}